-- Create default admin user for wedding registry
-- Username: admin
-- Password: wedding123
-- Note: Run scripts/setup-admin.mjs to create the user with proper password hash
-- This is kept for reference only

-- If you need to manually insert (use the hash generated by setup-admin.mjs):
-- INSERT INTO admin_users (username, password_hash, email) 
-- VALUES ('admin', 'HASH_FROM_SETUP_SCRIPT', 'admin@wedding-registry.local')
-- ON CONFLICT (username) DO NOTHING;
